export type TemplateCategory =
  | "tiktok" | "youtube" | "cinematic" | "podcast" | "ecommerce"
  | "viral_trends" | "gaming" | "fashion" | "real_estate" | "fitness"
  | "education" | "corporate" | "music" | "documentary" | "food" | "travel";

export interface VideoTemplate {
  id: string;
  name: string;
  category: TemplateCategory;
  aspectRatio: "16:9" | "9:16" | "1:1";
  duration: number;
  previewGradient: string;
  tracksCount: number;
  defaultLut?: string;
  defaultTrend?: string;
  defaultTransition?: string;
  description: string;
  tags: string[];
}

function t(
  id: string,
  name: string,
  category: TemplateCategory,
  aspectRatio: VideoTemplate["aspectRatio"],
  duration: number,
  previewGradient: string,
  tracksCount: number,
  description: string,
  tags: string[],
  defaults: Partial<VideoTemplate> = {}
): VideoTemplate {
  return { id, name, category, aspectRatio, duration, previewGradient, tracksCount, description, tags, ...defaults };
}

export const VIDEO_TEMPLATES: VideoTemplate[] = [
  t("tmpl_tiktok_hook", "TikTok Viral Hook & Captions", "tiktok", "9:16", 15, "from-fuchsia-600 to-rose-600", 4,
    "Fast hook text, animated captions, and a 4-track stack optimized for the TikTok algorithm.",
    ["hook", "captions", "shorts", "viral"],
    { defaultTrend: "trend_capcut_velocity", defaultTransition: "preset_strobe_flash" }),
  t("tmpl_yt_intro", "YouTube Tech Review Intro", "youtube", "16:9", 10, "from-blue-600 to-cyan-500", 5,
    "Clean lower thirds, cinematic intro banner, and punchy brand reveal for tech channels.",
    ["intro", "review", "lower-third", "tech"],
    { defaultTransition: "preset_kinetic_split_wipe" }),
  t("tmpl_cinematic_vlog", "Cinematic Travel Vlog LUT", "cinematic", "16:9", 30, "from-amber-600 to-orange-700", 6,
    "35mm film grain, teal & orange grade, and anamorphic flares for premium travel footage.",
    ["cinematic", "vlog", "film", "travel"],
    { defaultLut: "Teal_Orange_Cinematic.cube", defaultTransition: "preset_film_burn_wipe" }),
  t("tmpl_podcast_clip", "Podcast Audiogram + Waveform", "podcast", "1:1", 45, "from-emerald-600 to-teal-700", 3,
    "Dynamic audio waveform sync with voice auto-ducking for shareable podcast clips.",
    ["podcast", "audiogram", "waveform", "audio"],
    { defaultTrend: "trend_karaoke_glow" }),
  t("tmpl_ecom_promo", "E-Commerce Flash Sale Promo", "ecommerce", "9:16", 12, "from-violet-600 to-indigo-700", 4,
    "High-energy strobe transitions, sale callout arrows, and countdown pressure framing.",
    ["sale", "ecommerce", "promo", "offer"],
    { defaultTransition: "preset_strobe_flash" }),
  t("tmpl_gaming_montage", "Valorant/FPS Kill Montage Beat-Sync", "gaming", "16:9", 25, "from-rose-600 to-purple-800", 6,
    "Beat-synced kill-cam cuts, chromatic flashes, and screen-shake on every elim.",
    ["gaming", "montage", "valorant", "esports", "beat-sync"],
    { defaultTrend: "trend_capcut_velocity", defaultTransition: "preset_zoom_blur_transition" }),
  t("tmpl_fashion_lookbook", "Minimalist High-Fashion Lookbook", "fashion", "9:16", 18, "from-neutral-200 to-stone-800", 4,
    "Editorial minimal aesthetic with slow fades and elegant kinetic type.",
    ["fashion", "editorial", "minimal", "luxury"],
    { defaultLut: "Monochrome_High_Contrast.cube", defaultTransition: "preset_fade_in" }),
  t("tmpl_real_estate", "Luxury Architecture & Real Estate", "real_estate", "16:9", 40, "from-amber-400 to-amber-800", 5,
    "Golden-hour drone pans, slow cinematic pushes, and premium lower thirds for property tours.",
    ["realestate", "architecture", "drone", "luxury"],
    { defaultLut: "Warm_Golden_Hour.cube", defaultTransition: "preset_cinematic_zoom" }),
  t("tmpl_tech_unboxing", "Apple/Tech Aesthetic Unboxing", "youtube", "16:9", 20, "from-cyan-500 to-slate-900", 5,
    "Clean white-seam aesthetic with subtle parallax and product callouts.",
    ["unboxing", "apple", "tech", "product"],
    { defaultTransition: "preset_lower_third_bracket" }),
  t("tmpl_music_visualizer", "Neon EDM Audio Spectrum Visualizer", "music", "16:9", 60, "from-fuchsia-500 via-purple-600 to-cyan-400", 4,
    "Realtime WebAudio spectrum visualizer with neon glow and beat pulses.",
    ["music", "visualizer", "edm", "audio"],
    { defaultTrend: "trend_cyberpunk_flash" }),
  t("tmpl_doc_map", "Documentary 3D Animated Map & Timeline", "documentary", "16:9", 35, "from-stone-600 to-amber-900", 5,
    "Animated map routes, 3D timeline flourishes, and archive-film grain.",
    ["documentary", "map", "history", "timeline"],
    { defaultLut: "Kodak_Portra_400.cube" }),
  t("tmpl_fitness_timer", "HIIT Workout Interval & Rest Timer", "fitness", "9:16", 30, "from-orange-500 to-red-700", 4,
    "Big interval countdowns, rest/sprint overlays, and energetic beat cut-ins.",
    ["fitness", "hiit", "workout", "timer"],
    { defaultTrend: "trend_capcut_velocity", defaultTransition: "preset_zoom_boom_in" }),
  t("tmpl_course_intro", "Online Course Lesson Intro", "education", "16:9", 12, "from-sky-600 to-indigo-600", 4,
    "Friendly lesson intro with teacher name card and topic bullets.",
    ["education", "course", "teaching", "intro"],
    { defaultTransition: "preset_fade_in_up" }),
  t("tmpl_explainer", "Animated Explainer Lower-Thirds", "education", "16:9", 20, "from-teal-500 to-emerald-600", 4,
    "Icon callouts, keyword pops, and explainer-style captions.",
    ["explainer", "education", "callout", "motion-graphics"],
    { defaultTransition: "preset_callout_ping" }),
  t("tmpl_corporate_brand", "Corporate Brand Identity Kit", "corporate", "16:9", 15, "from-slate-600 to-blue-800", 5,
    "Logo coin-flip reveal, mission statement kinetic type, and executive lower thirds.",
    ["corporate", "brand", "company", "logo"],
    { defaultTransition: "preset_coin_flip_logo" }),
  t("tmpl_viral_challenge", "Viral Challenge Duet Starter", "viral_trends", "9:16", 20, "from-cyan-500 via-fuchsia-500 to-amber-400", 4,
    "Auto-reacts to trending sounds with beat markers, caption prompts, and duet layout.",
    ["challenge", "duet", "viral", "trending"],
    { defaultTrend: "trend_capcut_velocity" }),
  t("tmpl_news_brief", "Breaking News Lower-Third Pack", "corporate", "16:9", 25, "from-red-600 to-rose-800", 5,
    "Red alert banners, news swoosh lower thirds, and breaking ticker animations.",
    ["news", "breaking", "broadcast", "ticker"],
    { defaultTransition: "preset_lower_third_swoosh" }),
  t("tmpl_live_stream_alert", "Live Stream Donation Alerts", "gaming", "16:9", 10, "from-purple-600 to-pink-600", 3,
    "Stinger transitions, donation alert pops, and follow/sub goal trackers.",
    ["stream", "alert", "donation", "twitch"],
    { defaultTransition: "preset_zoom_boom_in" }),
  t("tmpl_food_recipe", "Recipe Steps Tutorial", "food", "9:16", 30, "from-orange-400 to-red-600", 4,
    "Ingredients list wipe, step numbers, and appetite-stimulating close-up pop-ins.",
    ["food", "recipe", "cooking", "tutorial"],
    { defaultLut: "Fuji_Velvia_50.cube", defaultTransition: "preset_scale_x_in" }),
  t("tmpl_travel_reel", "Travel Bucket-List Reel", "travel", "9:16", 22, "from-teal-400 to-cyan-600", 5,
    "Fast location-title pops, handheld footage, and trending-sound sync.",
    ["travel", "bucketlist", "reel", "destinations"],
    { defaultTrend: "trend_karaoke_glow" }),
  t("tmpl_motivational_speech", "Motivational Quote Video", "cinematic", "16:9", 18, "from-indigo-700 to-purple-900", 4,
    "Cinematic quote reveals with word-by-word kinetic type and slow zoom on b-roll.",
    ["motivation", "quotes", "speech", "cinematic"],
    { defaultTrend: "trend_cinematic_lut", defaultTransition: "preset_cinematic_zoom" }),
  t("tmpl_yt_vlog_setup", "Creator Routine Vlog Intro", "youtube", "16:9", 14, "from-amber-400 to-rose-500", 5,
    "Cozy creator intro with name lower-third, emoji callouts, and jitter text.",
    ["vlog", "creator", "routine", "intro"],
    { defaultTransition: "preset_elastic_bounce" }),
  t("tmpl_holiday_greeting", "Holiday Greeting Card", "corporate", "9:16", 12, "from-emerald-500 to-red-600", 4,
    "Confetti burst, warm text reveal, and sparkle overlays for holiday wishes.",
    ["holiday", "greeting", "celebration", "cards"],
    { defaultTransition: "preset_light_leak" }),
  t("tmpl_product_launch", "Product Launch Teaser", "ecommerce", "16:9", 16, "from-blue-700 to-black", 5,
    "Dark cinematic teaser with reveal-on-drop, spec callouts, and launch date countdown.",
    ["launch", "product", "teaser", "countdown"],
    { defaultTransition: "preset_3d_dolly_zoom" }),
  t("tmpl_dj_live_set", "DJ Live Set Teaser", "music", "9:16", 20, "from-fuchsia-600 to-purple-800", 4,
    "Strobe flashes, bass-drop visualizers, and venue title callouts.",
    ["dj", "club", "music", "nightlife"],
    { defaultTrend: "trend_cyberpunk_flash" }),
  t("tmpl_aesthetic_slideshow", "Aesthetic Photo Slideshow", "cinematic", "9:16", 25, "from-rose-300 to-amber-400", 3,
    "Soft ken-burns on stills, warm film LUT, and elegant fade transitions.",
    ["slideshow", "aesthetic", "photos", "film"],
    { defaultLut: "Fuji_Velvia_50.cube", defaultTransition: "preset_fade_in" }),
  t("tmpl_fitness_pose", "Gym Form Tutorial", "fitness", "9:16", 35, "from-lime-600 to-emerald-800", 4,
    "Slow-mo form analysis, muscle-group callouts, and rep counter overlays.",
    ["gym", "form", "tutorial", "fitness"],
    { defaultTransition: "preset_callout_pointer" }),
  t("tmpl_car_review", "Car Review POV Drive", "youtube", "16:9", 28, "from-slate-700 to-cyan-700", 5,
    "POV dash cam, spec-lower thirds, engine-sound waveform, and speed ramps.",
    ["car", "auto", "review", "pov"],
    { defaultTransition: "preset_zoom_blur_transition" }),
  t("tmpl_street_interview", "Street Interview B-Roll", "tiktok", "9:16", 18, "from-amber-500 to-orange-700", 4,
    "Rapid-fire interview edits with caption pops, buzz words, and audience-stopping hooks.",
    ["interview", "street", "viral", "hook"],
    { defaultTrend: "trend_capcut_velocity" }),
  t("tmpl_asmr", "ASMR Calm Ambience", "cinematic", "16:9", 40, "from-slate-400 to-amber-700", 3,
    "Gentle slow zooms, warm soft grade, and whisper-friendly waveform accents.",
    ["asmr", "calm", "ambience", "relax"],
    { defaultLut: "Warm_Golden_Hour.cube", defaultTransition: "preset_fade_in" }),
  t("tmpl_behind_scenes", "Behind The Scenes Vlog", "youtube", "16:9", 20, "from-neutral-500 to-stone-900", 5,
    "Fast BTS cuts, timestamp title cards, and creator shout-out lower thirds.",
    ["bts", "vlog", "creator", "behind-scenes"],
    { defaultTransition: "preset_kinetic_split_wipe" }),
  t("tmpl_makeup_tutorial", "Makeup Tutorial Step-By-Step", "fashion", "9:16", 26, "from-pink-400 to-rose-700", 4,
    "Product callout arrows, before/after wipe, and ingredient pop-ups.",
    ["makeup", "beauty", "tutorial", "fashion"],
    { defaultTransition: "preset_callout_ping" }),
  t("tmpl_gym_progress", "Gym Progress Journey", "fitness", "9:16", 24, "from-amber-500 to-red-700", 4,
    "Date stamp lower thirds, transformation wipe, and rep-count overlays.",
    ["gym", "progress", "transformation", "fitness"],
    { defaultTrend: "trend_capcut_velocity" }),
  t("tmpl_restaurant_menu", "Restaurant Menu Spotlight", "food", "9:16", 20, "from-red-500 to-orange-600", 4,
    "Dish close-up zooms, price callouts, and sizzle-sound sync.",
    ["restaurant", "menu", "food", "review"],
    { defaultLut: "Fuji_Velvia_50.cube" }),
  t("tmpl_hotel_review", "Hotel Room Tour Review", "travel", "16:9", 24, "from-teal-400 to-indigo-600", 5,
    "Room walkthrough pans, amenity callouts, and price-per-night lower thirds.",
    ["hotel", "review", "travel", "tour"],
    { defaultTransition: "preset_cinematic_zoom" }),
  t("tmpl_vertical_gadget", "Gadget Review Vertical", "tiktok", "9:16", 16, "from-cyan-500 to-slate-800", 4,
    "Specs flashed on beat, drop-test slow-mo, and verdict rating pop.",
    ["gadget", "review", "tech", "shorts"],
    { defaultTrend: "trend_cyberpunk_flash" }),
  t("tmpl_movie_trailer", "Movie Trailer Reveal", "cinematic", "16:9", 35, "from-zinc-700 to-red-900", 6,
    "Dark title-slam reveals, quick flash cuts, and dramatic score-sync beats.",
    ["trailer", "movie", "drama", "cinematic"],
    { defaultTransition: "preset_zoom_blur_transition", defaultLut: "ARRI_Alexa_Cinema.cube" }),
  t("tmpl_lyric_video", "Lyric Video Karaoke", "music", "9:16", 45, "from-fuchsia-500 via-purple-600 to-cyan-400", 4,
    "Word-by-word karaoke highlight, beat-waveform, and song-title drop.",
    ["lyrics", "karaoke", "music", "song"],
    { defaultTrend: "trend_karaoke_glow" }),
  t("tmpl_finance_tips", "Finance Tips Whiteboard", "education", "16:9", 22, "from-emerald-600 to-teal-900", 4,
    "Hand-drawn chart callouts, ROI number pops, and disclaimer lower thirds.",
    ["finance", "money", "tips", "education"],
    { defaultTransition: "preset_callout_pointer" }),
  t("tmpl_meditation", "Meditation Breathing Guide", "cinematic", "16:9", 60, "from-teal-400 to-emerald-800", 3,
    "Slow breathing-circle overlays, calm gradient washes, and gentle fade transitions.",
    ["meditation", "breathing", "calm", "wellness"],
    { defaultTransition: "preset_fade_in" }),
  t("tmpl_diy_howto", "DIY How-To Build", "education", "16:9", 30, "from-orange-500 to-yellow-700", 5,
    "Step-number pop-ins, tool callouts, and before/after build reveal.",
    ["diy", "howto", "build", "tools"],
    { defaultTransition: "preset_scale_x_in" }),
  t("tmpl_kids_edu", "Kids Educational Animation", "education", "9:16", 20, "from-sky-400 via-lime-400 to-amber-400", 4,
    "Playful emoji callouts, bright gradient title pops, and bouncy text.",
    ["kids", "education", "fun", "animation"],
    { defaultTrend: "trend_karaoke_glow" }),
  t("tmpl_sports_highlight", "Sports Highlight Reel", "gaming", "16:9", 20, "from-emerald-500 to-teal-800", 5,
    "Replay freeze-frame callouts, score bug lower thirds, and beat-sync cuts.",
    ["sports", "highlight", "replay", "score"],
    { defaultTransition: "preset_strobe_flash", defaultTrend: "trend_capcut_velocity" }),
  t("tmpl_fan_edit", "Celebrity Fan Edit", "viral_trends", "9:16", 15, "from-purple-600 via-pink-500 to-rose-600", 4,
    "Soft glows, aesthetic zoom pulses, and trending-sound lyric sync.",
    ["fan-edit", "aesthetic", "trending", "glow"],
    { defaultTrend: "trend_cyberpunk_flash", defaultTransition: "preset_light_leak" }),
  t("tmpl_greenscreen_pack", "Green Screen Sticker Pack", "viral_trends", "9:16", 12, "from-lime-400 to-emerald-700", 3,
    "Pop-on sticker frames, zoom reactions, and hype-beat cut-ins for green screen edits.",
    ["greenscreen", "stickers", "reaction", "meme"],
    { defaultTransition: "preset_zoom_boom_in" }),
  t("tmpl_ai_news_recap", "AI News Recap Short", "education", "9:16", 25, "from-cyan-500 via-sky-600 to-indigo-700", 5,
    "Headline pop-ins, stat callouts, and kinetic captions built for AI-news channels.",
    ["news", "ai", "recap", "captions"],
    { defaultTrend: "trend_alex_hormozi", defaultTransition: "preset_kinetic_split_wipe" }),
  t("tmpl_fitness_pt", "Personal Trainer Workout", "fitness", "9:16", 40, "from-orange-500 via-red-600 to-rose-700", 5,
    "Exercise rep counters, rest-timer lower thirds, and high-BPM beat cuts.",
    ["fitness", "gym", "workout", "reps"],
    { defaultTrend: "trend_capcut_velocity", defaultTransition: "preset_strobe_flash" }),
  t("tmpl_food_asmr", "Food ASMR Close-Up", "food", "9:16", 20, "from-amber-500 via-orange-600 to-red-700", 4,
    "Slow-mo zoom pulses, sizzle-synced flashes, and ingredient callouts.",
    ["food", "asmr", "cooking", "recipe"],
    { defaultTrend: "trend_cyberpunk_flash" }),
  t("tmpl_realestate_lux", "Luxury Real Estate Tour", "real_estate", "16:9", 35, "from-stone-400 via-amber-600 to-stone-800", 6,
    "Slow push-ins, property lower thirds, and premium cream color grade.",
    ["real-estate", "luxury", "tour", "cinematic"],
    { defaultLut: "Teal_Orange_Cinematic.cube", defaultTransition: "preset_ken_burns_in" }),
  t("tmpl_shortfilm_doc", "Short Documentary Teaser", "documentary", "16:9", 30, "from-zinc-700 via-stone-600 to-neutral-900", 5,
    "Letterbox cinematic bars, film grain, and dramatic quote reveals.",
    ["documentary", "short-film", "cinematic", "quotes"],
    { defaultLut: "Moody_Teal.cube", defaultTransition: "preset_film_burn_wipe" }),
  t("tmpl_shopify_dropship", "Shopify Dropship Ad", "ecommerce", "9:16", 15, "from-blue-600 via-indigo-600 to-violet-700", 4,
    "Benefit callout pops, social-proof tickers, and CTA flash cards.",
    ["shopify", "dropship", "ads", "cta"],
    { defaultTrend: "trend_capcut_velocity", defaultTransition: "preset_zoom_punch_scale" }),
  t("tmpl_fashion_lookbook", "Fashion Lookbook Reel", "fashion", "9:16", 18, "from-neutral-200 via-rose-300 to-fuchsia-500", 4,
    "Runway zoom pulses, brand-name kinetic type, and soft glow transitions.",
    ["fashion", "lookbook", "runway", "glow"],
    { defaultTransition: "preset_light_leak", defaultTrend: "trend_karaoke_glow" }),
  t("tmpl_league_clip", "Gaming Clutch Highlight", "gaming", "16:9", 20, "from-rose-600 via-purple-700 to-indigo-800", 5,
    "Kill-feed callouts, clutch-moment zoom punch, and beat-sync streaks.",
    ["gaming", "clutch", "highlight", "killfeed"],
    { defaultTransition: "preset_glitch", defaultTrend: "trend_capcut_velocity" }),
  t("tmpl_music_visualizer", "Music Visualizer Loop", "music", "16:9", 30, "from-fuchsia-500 via-purple-600 to-cyan-500", 5,
    "Tone.js waveform sync, spectrum flashes, and lyric kinetic type.",
    ["music", "visualizer", "waveform", "audio"],
    { defaultTrend: "trend_karaoke_glow", defaultTransition: "preset_pulse" })
];

export const VIDEO_TEMPLATES_BY_ID: Record<string, VideoTemplate> = Object.fromEntries(
  VIDEO_TEMPLATES.map((p) => [p.id, p])
);

export function getVideoTemplate(id: string | null | undefined): VideoTemplate | undefined {
  return id ? VIDEO_TEMPLATES_BY_ID[id] : undefined;
}

export const TEMPLATE_CATEGORIES: TemplateCategory[] = Array.from(
  new Set(VIDEO_TEMPLATES.map((tmpl) => tmpl.category))
);
